// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about/[name].tsx";
import * as $3 from "./routes/about/index.tsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/cv/[language].tsx";
import * as $6 from "./routes/cv/entry.tsx";
import * as $7 from "./routes/cv/index.tsx";
import * as $8 from "./routes/greet/[name].tsx";
import * as $9 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about/[name].tsx": $2,
    "./routes/about/index.tsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/cv/[language].tsx": $5,
    "./routes/cv/entry.tsx": $6,
    "./routes/cv/index.tsx": $7,
    "./routes/greet/[name].tsx": $8,
    "./routes/index.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
